add types, id, index, fix multipolygon, prettier
2gis/geojson-vt pull request #1
Opened 2021-06-09 05:26 UTC by vitaliy-gis

Добавлена типизация
Проброшены id объектов и порядковый номер в массиве
Изменена структура координат полигона и мультиполигона: теперь Polygon и Maultipolygon всегда возвращают массив полигонов (а не массив колец как было ранее)

2021-06-10 04:06 UTC, Trufi requested changes

2021-06-10 04:06 UTC, Trufi commented on package.json
> +    "version": "1.0.0",
В таких случаях, принято оставлять версию исходного пакета, чтобы их можно было сматчить

2021-06-10 04:06 UTC, Trufi commented on package.json
> +    ]
Если мы хотим засылать улучшалки в исходный пакет, то не надо менять так форматирование во всем файле

2021-06-10 04:06 UTC, Trufi commented on src/clip.js
> +    // trivial accept
Опять же, зачем эти изменения? Они нам встанут боком, если мы захотим изменения в исходный пакет засылать

2021-06-10 04:06 UTC, Trufi commented on types.d.ts
> +interface TileFeaturePolygons extends TileFeatureBase {
Любой тип, который используется в экспортируемых типах, должен тоже экспортироваться. Так пакет с типами будет намного удобней использовать.

Это относится и к типам выше.

2021-06-10 04:10 UTC, Trufi commented on types.d.ts
> +    Points = 1,
Типы фич лучше назвать в единственном числе. Зачем множественное?

2021-06-10 04:23 UTC, vitaliy-gis commented on types.d.ts
> +    Points = 1,
Что бы явно указать что эти типы multipart. Избежать коллизии с типами GeoJSON

2021-06-11 06:38 UTC, Trufi commented on types.d.ts
> +    Points = 1,
Тогда непонятно, почему енам называется GeoJsonFeatureType. Здесь уже говорится о том, что это тип фичи GeoJSON. А тип у фич какой бывает там? Point, LineString, Polygon, MultiPoint, MultiLineString, MultiPolygon, GeometryCollection

2021-06-11 09:13 UTC, Trufi approved these changes

2021-06-17 04:48 UTC, merged